version: '2'
services:
  mongo-primary:
    build: .
    expose: [27017,27018,27019]
    ports:
      - 27017:27017
  mongo-arbitre:
    build: .
    expose: [27017,27018,27019]
  mongo-secondary-a:
    build: .
    expose: [27017,27018,27019]
  mongo-secondary-b:
    build: .
    expose: [27017,27018,27019]
