version: '2'
services:
  mongo-router-a:
    build: .
    expose: [27017,27018,27019]
    ports:
      - 27017:27017
  mongo-router-b:
    build: .
    expose: [27017,27018,27019]
  mongo-config-a:
    build: .
    expose: [27017,27018,27019]
  mongo-config-b:
    build: .
    expose: [27017,27018,27019]
  mongo-config-c:
    build: .
    expose: [27017,27018,27019]
  mongo-shard-rs-a:
    build: .
    expose: [27017,27018,27019]
  mongo-shard-rs-b:
    build: .
    expose: [27017,27018,27019]
